/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.marcbender.emitterview;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;

import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;

import android.os.Bundle;
import android.view.View;


@Kroll.module(name = "TiView", id = "de.marcbender.emitterview")
public class TiEmitterViewModule extends KrollModule
{
	// Standard Debugging variables
	private static final String LCAT = "DeMarcbenderEmitterViewModule";
	private static final boolean DBG = TiConfig.LOGD;

	public TiEmitterViewModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
	}



}
