/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.marcbender.emitterview;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;

import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;

import android.os.Bundle;
import android.view.View;


@Kroll.module(name = "TiView", id = "de.marcbender.emitterview")
public class TiEmitterViewModule extends KrollModule
{
	// Standard Debugging variables
	private static final String LCAT = "DeMarcbenderEmitterViewModule";
	private static final boolean DBG = TiConfig.LOGD;

	// Particle Type Constants (accessible via require('de.marcbender.emitterview').PARTICLE_*)
	@Kroll.constant public static final int PARTICLE_CUSTOM = 0;
	@Kroll.constant public static final int PARTICLE_CONFETTI = 1;
	@Kroll.constant public static final int PARTICLE_TRIANGLE = 2;
	@Kroll.constant public static final int PARTICLE_STAR = 3;
	@Kroll.constant public static final int PARTICLE_DIAMOND = 4;
	@Kroll.constant public static final int PARTICLE_TEXT = 5;

	// Direction Constants (accessible via require('de.marcbender.emitterview').DIRECTION_*)
	@Kroll.constant public static final int DIRECTION_UP = 0;
	@Kroll.constant public static final int DIRECTION_DOWN = 1;
	@Kroll.constant public static final int DIRECTION_LEFT = 2;
	@Kroll.constant public static final int DIRECTION_RIGHT = 3;

	public TiEmitterViewModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
	}



}
